### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by tv42** [cespare/sub#8]
I got a bunch of "Too many open files" errors and stared at the sub code for all too long before I realized go get had fetched v0.1.1 and master had a bunch of commits after that. Please tag v0.2.0 or such.

**Comment by tv42** [comment]
(To add insult to injury, this seems to second time I'm stumbling on that: https://github.com/cespare/sub/issues/7 )

**Comment by cespare** [comment]
Tagged 0.2.0.
