### ISSUE TITLE
`$` never matches anything

### ISSUE THREAD

**Issue by tv42** [cespare/sub#9]
```
echo foo >f
sub -v -d 'foo$' foundit f
sub -v -d 'foo' workswithoutdollar f
```

I expected `$` to match the end of line. A quick skim of the source didn't give me an explanation why it wouldn't...

**Comment by tv42** [comment]
Oh now I know, it's because https://golang.org/pkg/bytes/#Buffer.ReadBytes leaves the `\n` in the result.

**Comment by cespare** [comment]
Looks like I was writing this tool right at the same time that Go 1.1 (with bufio.Scanner) was being released.

It's a lot more convenient to use Scanner, though it means we can't tell if the last line has an ending `\n` or not, so now sub will add a `\n` to a file that didn't have the terminating newline before. I like the terminating newlines anyway, so seems fine to me.
